config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :posts do
      resources :likes,only: [:create,:destroy]
      resources :comments
    end  
  end  
  resources :sessions, only: [:new, :create, :destroy]
  root "sessions#new"
  get "users/view/:id",to: "users#view"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes
  has_many :comments
  has_one_attached :image,:dependent => :destroy
end

app/models/user.rb
class User < ApplicationRecord
    include ActiveModel::Serialization
    has_secure_password
    validates :email, uniqueness: true
    has_one_attached :image,:dependent => :destroy
    has_many :posts,:dependent => :destroy

    def welcome
        "#{self.image}"
        "Username: #{self.email}"
    end
    
    def capitalized_name
        name.capitalize
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :require_login
    helper_method :current_user

    def require_login
        redirect_to new_session_path unless session.include? :user_id
    end

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        @post=Post.find(params[:post_id])
        @like=@post.likes.build
        if @like.save
            @like.update(count:@post.likes.count)
            flash[:success]="Post Liked!"
        else
            flash[:error]="Failed to like the post!"
        end
        redirect_to user_path(@post.user, @post)      
    end    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    skip_before_action :require_login, only: [:new, :create,:index]
    before_action :get_id
    def index
    end

    def show
        @post=@user.posts.find(params[:id])
    end

    def view
    end
    
    def new
        @post = @user.posts.build
    end
    
    def create
        @post = @user.posts.build(post_params)
        if @post.save
        redirect_to user_path(current_user.id),notice:"Post was Successfully created!"
        else
        flash[:error] = "Error- please try to create an account again."
        redirect_to new_user_post_path
        end
    end

    def edit
    end

    def update
        if @post.update(post_params)
        redirect_to @post
        else
        render edit_post_path
        end   
    end
    
    def destroy
        debugger
        if @post.destroy
        flash[:notice]="Successfully deleted"
        redirect_to posts_path
        end
    end  
    
    private
    def get_id
        @user=User.find(params[:user_id])
    end  
    def post_params
        params.require(:post).permit(:description,:image)
    end    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:create, :new]
  def new
  end

  def create
      session_params = params.permit(:email, :password)
      @user = User.find_by(email: session_params[:email])
      if @user && @user.authenticate(session_params[:password])
        session[:user_id] = @user.id
        redirect_to @user
      else
        flash[:notice] = "Login is invalid!"
        redirect_to new_session_path
      end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You have been signed out!"
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :require_login, only: [:new, :create,:index]
    before_action :get_id,only: [:show,:view,:edit,:update,:destroy]
    def index
      @users=User.all.with_attached_image
      # render json: @users, user: ::UserSerializer
    end

    def show
        if @user.posts.any?
            @posts=@user.posts
        else
          render :show
        end
    end

    def view
        if @user.posts.any?
          @posts=@user.posts
        else
          render :show
        end
    end
  
    def new
      @user = User.new
    end
  
    def create
      @user = User.create(user_params)
      if @user.valid?
        session[:user_id] = @user.id
        redirect_to @user
      else
        flash[:error] = "Error- please try to create an account again."
        redirect_to new_user_path
      end
    end

    def edit
    end

    def update
       if @user.update(user_params)
        redirect_to @user
       else
        render edit_user_path
       end   
    end
    
    def destroy
      if @user.destroy
      flash[:notice]="Successfully deleted"
      redirect_to users_path
      end
    end  
  
    private
    def get_id
      @user=User.find(params[:id])
    end  
    def user_params
      params.require(:user).permit(:id,:email, :password, :image,:name,:bio)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Searchlight</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/likes/create.html.erb
<h1>Likes create</h1>

app/views/likes/index.html.erb
<h1>Likes Index</h1>

app/views/posts/_form.html.erb
<%= form_with(model:[@user,@post],url:user_posts_path(@user),method: :post,local:true) do |form| %>

    <div>
    <%= form.label :Post%>    <br>
    <%= form.file_field :image %>
    </div>

    <div>
    <%= form.label :Caption%>    <br>
    <%= form.text_field :description %>
    </div>

    <%= form.submit "POST" %><br><br>
<% end %>

app/views/posts/new.html.erb
<%= stylesheet_link_tag "posts_new.css" %>
<h1> New Post</h1>            
<%= render "form"%>

app/views/posts/show.html.erb
<%= stylesheet_link_tag "posts_show.css" %>

<nav class="navbar navbar-light">
  <%= link_to 'Explore', users_path %>
  <%= image_tag(url_for(current_user.image), class: "resize-profile") if current_user.image.attached? %>
  <%= content_tag :h6, current_user.welcome %>
  <%= link_to "Sign out", new_session_path, data: { "turbo-method": :delete,"turbo_confirm": "Are you sure,You want to sign out!" } %>
</nav>
<div class="post_show">
    <%= image_tag(url_for(@post.image)) if @post.image.attached? %>
</div>

app/views/users/_attachment.html.erb
<% if @user.image.attached? %>
   <div>
        <%= image_tag(url_for(@user.image),class:"resize-image") %>
   </div>
<% end %>

app/views/users/_form.html.erb
<%= stylesheet_link_tag "users_form.css" %>

<% if @user.errors.any? %>
  <div class="alert alert-danger">
    <h4><%= pluralize(@user.errors.count, "error") %> prohibited this friend from being saved:</h4>

    <ul>
      <% @user.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @user do |form| %>
  <div class="form-group">
    <%= form.label :email, class: "form-label" %>
    <%= form.text_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :password, class: "form-label" %>
    <%= form.password_field :password, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :bio, class: "form-label" %>
    <%= form.text_field :bio, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :profile, class: "form-label" %>
    <%= form.file_field :image, class: "form-control-file" %>
  </div>

  <%= form.submit "SUBMIT", class: "btn btn-primary" %>
<% end %>

app/views/users/_preview.html.erb
<%= stylesheet_link_tag "users_show.css" %>
<nav class="navbar navbar-light">
  <%= link_to 'Explore', users_path %>
  <%= image_tag(url_for(current_user.image), class: "resize-profile") if current_user.image.attached? %>
  <%= content_tag :h6, current_user.welcome %>
  <%= link_to "Sign out", new_session_path, data: { "turbo-method": :delete,"turbo_confirm": "Are you sure,You want to sign out!" } %>
</nav>

<div class="profile-container">
  <div class="media border p-3">
    <%= render 'users/attachment' %>
    <div class="profile-details">
      <h2><%= @user.name %></h2>
      <p><strong>Bio:</strong> <%= @user.bio %></p>
    </div>
    <% if current_user == @user %>
        <div class="profile-actions">
        <%= link_to 'Edit profile', edit_user_path, class: "btn btn-primary" %>
        <%= link_to 'Create a new Post', new_user_post_path(@user), class: "btn btn-primary" %>
        <%= link_to 'Delete account', user_path(@user),data: { turbo_method: :delete,turbo_confirm: 'Are you sure,You want to delete account?' }, class: "btn btn-primary" %>
        </div>
    <% end %>
  </div>
</div>

<% if @user.posts.any? %>
<div class="posts-container">
  <% @posts.each do |post| %>
    <div class="post">
      <%= image_tag(url_for(post.image), class: "resize-post") if post.image.attached? %>
      <h6><%= post.description %></h6><br>
      <%= link_to "View Post",user_post_path(current_user.id,post.id),class: "btn-primary" %>
      <%= button_to "Like","/users/#{current_user.id}/posts/#{post.id}/likes", class: "btn-primary" %>
      Likes-<%= post.likes.count %>
    </div>
  <% end %>
<% end %>
</div>

app/views/users/edit.html.erb
<h1> Edit Profile</h1>        

<%= render "form" %>

app/views/users/index.html.erb
<%= stylesheet_link_tag "users_index.css" %>

<div class="Link">
<%= link_to 'LOG IN/SIGN UP',new_session_path %>
</div>
<div class="text-center">
<h1> USERS </h1>
</div>
<table class="table">
    <thead>
        <tr>
            <th>S/No</th>
            <th>Profile</th>
            <th>Name</th>
            <th>Bio</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <% $i=1%>
        <% @users.each do |user| %>
        <tr>
            <td><%= $i %></td>
            <td> <% if user.image.attached? %>
                        <div>
                            <%= image_tag(url_for(user.image),class:"resize-image-index") %>
                        </div>
                <% end %>
            </td>
            <td><%= user.name %></td>
            <td><%= user.bio %></td>
            <td><%= link_to 'View Profile',"/users/view/#{user.id}" %></td>
        <% $i+=1 %>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/users/new.html.erb
<h1> New User</h1>            

<%= render "form" %>

app/views/users/show.html.erb
<%= render "preview" %>

app/views/users/view.html.erb
<%= render "preview" %>